export const FETCH_PAINTINGS = 'FETCH_PAINTINGS';
export const SELECT_ACTIVE_PAINTING = 'SELECT_ACTIVE_PAINTING';
export const DELETE_ACTIVE_PAINTING = 'DELETE_ACTIVE_PAINTING';
export const FILTER_PAINTINGS = 'FILTER_PAINTINGS';
